//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab04_MatthewMikhaiel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddresses
    {
        public int AddressID { get; set; }
        public string ModifiedDate { get; set; }
        public int CustomerID { get; set; }
        public string AddressType { get; set; }
        public int CustomerCustomerId { get; set; }
        public int AddressAddressId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Address Address { get; set; }
    }
}
